# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Rule clone

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Clone respository
      run: |
        git clone https://github.com/zhaobozhen/LibChecker-Rules
    - name: Run clone script
      run: |
        rm LibChecker-Rules.json -f
        python clone.py
        rm LibChecker-Rules -rf
    - name: Commit data
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "Github Action"
        git add LibChecker-Rules.json
        git commit -m "Clone rule"
        git push
